// <auto-generated />
using LuanDonde.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TransformaSeu.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuanDonde.Models.AssessmentForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyCNPJ")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CompanyRevenue")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CompanySector")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CompanySize")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CompanySocialName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CompanyState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Cultura1")
                        .HasColumnType("int");

                    b.Property<int>("Cultura2")
                        .HasColumnType("int");

                    b.Property<int>("Cultura3")
                        .HasColumnType("int");

                    b.Property<int>("Cultura4")
                        .HasColumnType("int");

                    b.Property<int>("Cultura5")
                        .HasColumnType("int");

                    b.Property<int>("Cultura6")
                        .HasColumnType("int");

                    b.Property<double>("CulturaFinal")
                        .HasColumnType("float");

                    b.Property<double>("CulturaMedia")
                        .HasColumnType("float");

                    b.Property<int>("CulturaPeso")
                        .HasColumnType("int");

                    b.Property<int>("CulturaTotal")
                        .HasColumnType("int");

                    b.Property<int>("Dados1")
                        .HasColumnType("int");

                    b.Property<int>("Dados2")
                        .HasColumnType("int");

                    b.Property<int>("Dados3")
                        .HasColumnType("int");

                    b.Property<int>("Dados4")
                        .HasColumnType("int");

                    b.Property<int>("Dados5")
                        .HasColumnType("int");

                    b.Property<double>("DadosFinal")
                        .HasColumnType("float");

                    b.Property<double>("DadosMedia")
                        .HasColumnType("float");

                    b.Property<int>("DadosPeso")
                        .HasColumnType("int");

                    b.Property<int>("DadosTotal")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Experiencia1")
                        .HasColumnType("int");

                    b.Property<int>("Experiencia2")
                        .HasColumnType("int");

                    b.Property<int>("Experiencia3")
                        .HasColumnType("int");

                    b.Property<int>("Experiencia4")
                        .HasColumnType("int");

                    b.Property<int>("Experiencia5")
                        .HasColumnType("int");

                    b.Property<int>("Experiencia6")
                        .HasColumnType("int");

                    b.Property<double>("ExperienciaFinal")
                        .HasColumnType("float");

                    b.Property<double>("ExperienciaMedia")
                        .HasColumnType("float");

                    b.Property<int>("ExperienciaPeso")
                        .HasColumnType("int");

                    b.Property<int>("ExperienciaTotal")
                        .HasColumnType("int");

                    b.Property<int>("Inovacao1")
                        .HasColumnType("int");

                    b.Property<int>("Inovacao2")
                        .HasColumnType("int");

                    b.Property<int>("Inovacao3")
                        .HasColumnType("int");

                    b.Property<int>("Inovacao4")
                        .HasColumnType("int");

                    b.Property<double>("InovacaoFinal")
                        .HasColumnType("float");

                    b.Property<double>("InovacaoMedia")
                        .HasColumnType("float");

                    b.Property<int>("InovacaoPeso")
                        .HasColumnType("int");

                    b.Property<int>("InovacaoTotal")
                        .HasColumnType("int");

                    b.Property<double>("MaturidadeDigital")
                        .HasColumnType("float");

                    b.Property<int>("Mercado1")
                        .HasColumnType("int");

                    b.Property<int>("Mercado2")
                        .HasColumnType("int");

                    b.Property<int>("Mercado3")
                        .HasColumnType("int");

                    b.Property<int>("Mercado4")
                        .HasColumnType("int");

                    b.Property<double>("MercadoFinal")
                        .HasColumnType("float");

                    b.Property<double>("MercadoMedia")
                        .HasColumnType("float");

                    b.Property<int>("MercadoPeso")
                        .HasColumnType("int");

                    b.Property<int>("MercadoTotal")
                        .HasColumnType("int");

                    b.Property<int>("Modelos1")
                        .HasColumnType("int");

                    b.Property<int>("Modelos2")
                        .HasColumnType("int");

                    b.Property<int>("Modelos3")
                        .HasColumnType("int");

                    b.Property<int>("Modelos4")
                        .HasColumnType("int");

                    b.Property<double>("ModelosFinal")
                        .HasColumnType("float");

                    b.Property<double>("ModelosMedia")
                        .HasColumnType("float");

                    b.Property<int>("ModelosPeso")
                        .HasColumnType("int");

                    b.Property<int>("ModelosTotal")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Processos1")
                        .HasColumnType("int");

                    b.Property<int>("Processos2")
                        .HasColumnType("int");

                    b.Property<int>("Processos3")
                        .HasColumnType("int");

                    b.Property<int>("Processos4")
                        .HasColumnType("int");

                    b.Property<int>("Processos5")
                        .HasColumnType("int");

                    b.Property<double>("ProcessosFinal")
                        .HasColumnType("float");

                    b.Property<double>("ProcessosMedia")
                        .HasColumnType("float");

                    b.Property<int>("ProcessosPeso")
                        .HasColumnType("int");

                    b.Property<int>("ProcessosTotal")
                        .HasColumnType("int");

                    b.Property<string>("RolePosition")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Tecnologia1")
                        .HasColumnType("int");

                    b.Property<int>("Tecnologia2")
                        .HasColumnType("int");

                    b.Property<int>("Tecnologia3")
                        .HasColumnType("int");

                    b.Property<int>("Tecnologia4")
                        .HasColumnType("int");

                    b.Property<int>("Tecnologia5")
                        .HasColumnType("int");

                    b.Property<double>("TecnologiaFinal")
                        .HasColumnType("float");

                    b.Property<double>("TecnologiaMedia")
                        .HasColumnType("float");

                    b.Property<int>("TecnologiaPeso")
                        .HasColumnType("int");

                    b.Property<int>("TecnologiaTotal")
                        .HasColumnType("int");

                    b.Property<bool>("TermosDeUso")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Formularios");
                });
#pragma warning restore 612, 618
        }
    }
}
